apiVersion: v1
kind: Service
metadata:
  name: laravel-app
  labels:
    app: laravel-app
spec:
  selector:
    app: laravel-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: ClusterIP
