apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bida-moha-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: bida-moha.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bida-moha-api
                port:
                  number: 80
