apiVersion: v1                     # Kubernetes API version for this object
kind: Service                      # This resource is a Service
metadata:
  name: taskmaster-svc             # Name of the Service
spec:
  selector:
    app: taskmaster                # Matches pods with label app=taskmaster
  ports:
    - protocol: TCP                # TCP protocol
      port: 80                     # Service port (external to cluster)
      targetPort: 5000             # Pod/container port to forward traffic to
      nodePort: 30007              # NodePort for external access (host:30007)
  type: NodePort                   # Exposes service externally via a port on each node

